### ISSUE TITLE
No official site/url for the book.

### ISSUE THREAD

**Issue by KristianLyng** [KristianLyng/varnishfoo#9]
Yes, I publish chapters on my blog, but I want a link for the book.

So far there's not a big need, but it would be nice in the future once a couple more chapters are in progress/"done".

**Comment by huayra** [comment]
varnishfoo.github.io ?

Github pages seems to be the new black...

**Comment by KristianLyng** [comment]
I considered varnishfoo.bar but .bar domains are 3x more expensive than any other vanity TLD out there. Not sure github pages are the way to go, github seems to love md too much, and I don't like perl :package: AASFASF !!!

Not :package:, I want to write :P and hit enter!

I hate you, github markup auto-completion bullshit....

Ok, so like I was saying, I don't know if github pages are the way to go, but I suppose I should check it out.

**Comment by KristianLyng** [comment]
Ok, I checked it out. I don't like the way it's maintained, and the only way to get a proper url is to either have an organization or account named 'varnishfoo', which isn't going to happen any time soon.

**Comment by KristianLyng** [comment]
See http://varnishfoo.info :D
